### ISSUE TITLE
how to guide doc?

### ISSUE THREAD

**Issue by kzkpro** [ureyni/wso2-wsf-php-2.1.0_rpm#1]
is there any instruction or doc on how to install or configure this library?

**Comment by ureyni** [comment]
i added install document.
if you get and  error while install ,i try to help.

**Comment by kzkpro** [comment]
Hello
Thanks for quick reply!

i'm on mac os x 10.9.5. running my php app in AMPPS.  earlier i tried this repo https://github.com/techhead/wsf/tree/master/php . it was straight forward and easy to compile and generate wsf extension . but i keep getting this error:

krozero-2:php kishorkhambu$ php
PHP Warning:  PHP Startup: Unable to load dynamic library '/Applications/AMPPS/php-5.3/lib/extensions/ext/wsf.so' - dlopen(/Applications/AMPPS/php-5.3/lib/extensions/ext/wsf.so, 9): image not found in Unknown on line 0

so then i found your repo wso2-wsf-php-2.1.0_rpm. cloned it and ran the readme commands

rpmbuild -bb -vv --buildroot "/tmp/axis2c-src-1.6.0-1.el6.x86_64" SPECS/axis2-apache.spec>axis2-apache.spec.log 2>&1

and 

rpmbuild -bb -vv --buildroot "/tmp/wso2-wsf-php53-2.1.0-1.el6.x86_64" SPECS/wsf-apache-server.spec>wsf-apache-server.spec.log 2>&1

but nothing happened. can you please provide step by step guide? and i'm new to rpm command line and its bit confusing. 

Thanks,
Kishor

**Comment by ureyni** [comment]
Hello 
i newer work on mac os.
rpm packages are run on centos,fedora,redhat.
mac os is not found wsf.so.
is there really wsf.so.
you can find wsf.so file or wsf.\* 
if is there ,change path name in php.ini file.
all i know mac os base on bsd.
may be you are compile from source code.

**Comment by kzkpro** [comment]
but is'n it a same if i install rpm on mac and run those rpmbuild commands? what does that script really do? can you please explain in bit more detail? does it creates a files in /tmp/... ? or do something else.   thanks!

**Comment by ureyni** [comment]
rpmbuild command create rpm from source code.Rpm shortcut name mean is readhat package manager.all i know Redhat base on linux but mac os base on unix.

"rpmbuild -bb -vv --buildroot "/tmp/wso2-wsf-php53-2.1.0-1.el6.x86_64" SPECS/wsf-apache-server.spec>wsf-apache-server.spec.log 2>&1" 
This Script compile from source code via config file (SPECS/wsf-apache-server.spec) and create rpm package.to form  rpm package in "/tmp/wso2-wsf-php53-2.1.0-1.el6.x86_64" directory.
and all output forward to wsf-apache-server.spec.log log file.
2>&1 mean is customer info,errors..etc and system error...etc direct is log file.

i talked my friend who use macbook retina about this subject.
he said , there is convert program rpm to mac os package 
and mac os have gcc compiler.may be compile from source code.

**Comment by kzkpro** [comment]
Hello, Thanks a lot for the help and support. i've successfully generated php extension by switching into  fedora. i have one more question, which may not related with setups. at first i thought it is a missing package (package that is used in java apps to authenticate wso2 user ) for php.  but looks like it's just a library to make different secure connection for php apps?

what i am looking is the way to authenticate wso2 identity server users in php app. i searched a lot but cant find reliable tutorials, samples or docs. 
i found this: 
    $client = new WSClient(array(                     "to" => "http://localhost/service.php",
                     "httpAuthUsername" => "username",
                     "httpAuthPassword" => "password",
                     "httpAuthType" => "Basic"));
some where, but not sure how backend (service.php) looks like. is there a way to authenticate wso2 users?. hope you are still using the library, if you do can you please share some of your knowledge about  this package? like good tutorials/articles or any thing that can help me in authenticating wso2 users. i'm new to wso2 and this package so, may be i'm missing many things. 
I would really appreciate your help. Many Thanks!

**Comment by ureyni** [comment]
Hello

did you look this http://wso2.com/project/wsf/php/2.0.0/docs/manual.html
web site.

**Comment by kzkpro** [comment]
yea, but i couldn't find what i need. i was trying to find a similar way to  authenticate user http://blog.facilelogin.com/2010/05/managing-users-and-roles-with-wso2.html using php. any idea how it can be done using php. 

Thanks!

**Comment by ureyni** [comment]
Hi ..

WSO2 is enterprise server bus and good application.If we want to use,we
have to a lot informtion about WSO2 esb.

must be install wso2.

after use WSO2 Identity Server
we decide what is need ?

WSO2 Identity Server is enterprise product and we have to expert for use.
are we need only user authenticate via web service?
we want to password and username from web service client in wsdl parameters
...next we compare password and username my data in database , result is
true or false..
others ways, use  securityToken ...
good day..

**Comment by kzkpro** [comment]
Thanks @ureyni , can you provide me with some clue. i see many tutorials for java based app but i can find any for php. is there way like: 

$client = new WSClient(array( "to" => "url to wso2 authentication server",
"httpAuthUsername" => "username",
"httpAuthPassword" => "password",
"httpAuthType" => "Basic"));

?  there's a java base app that is already using wso2 services. now i need to implement same in php app. mainly authenticating wso2 users. can you please provide some sample login scripts like how you guys do it, may be that will help me understand better. I would really appreciate your help. Thanks again!

**Comment by ureyni** [comment]
Hi.

```
$client = new WSClient(array("wsdl" => array(
        "httpAuthUsername" => "hucak",
        "httpAuthPassword" => "123456",
        "httpAuthType" => "Basic",
        "wsdl" => "http://localhost/fileUploadServer/FileUploadWSDL.php
```

"),
        //"securityToken" => $security_obj,
        //"Policy" => $policy_obj,
        "classmap" => $class_map));

this is sample is apache http server authentication.if user login to to for
get web service url , We can use it to apache http server(
http://httpd.apache.org/docs/2.2/howto/auth.html)

Apache's http config is

<Directory /opt/myprojects/wso2-wsf-php-2.1.0_rpm/samples>
    AuthType Basic
    AuthName "Only You"
    AuthUserFile /opt/apache2/password/passwords
    AllowOverride None
    Options None
    #Require all granted
    Require user hucak
</Directory>

securityToken and policy parameters is relevant oasis  web service securty..

good day.
